# Generated by Django 3.2.9 on 2022-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=False, verbose_name='Наличие карты памяти'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объем карты памяти'),
        ),
    ]
